local: &local
  secret_key_base: 7f8ca580757f6198cbabccd69968973b4a221521345d3eb024b61894bf44d51a8dc3771a7c223468f709d6dc75bab49f35eeeccb97b0b5c61b2b5159ceb80ebd
  redis_url: 'redis://localhost:6379'

development:
  <<: *local

test:
  <<: *local

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  redis_url: <%= ENV["REDIS_URL"] %>
